INSERT INTO team (name, code, score, confederation, league, team_type) VALUES
('France', 'FRA', 85, 'UEFA', NULL, 'NATIONAL'),
('England', 'ENG', 84, 'UEFA', NULL, 'NATIONAL'),
('Germany', 'GER', 84, 'UEFA', NULL, 'NATIONAL'),
('Spain', 'SPA', 84, 'UEFA', NULL, 'NATIONAL'),
('Argentina', 'ARG', 84, 'CONMEBOL', NULL, 'NATIONAL'),
('Portugal', 'POR', 83, 'UEFA', NULL, 'NATIONAL'),
('Netherlands', 'NET', 83, 'UEFA', NULL, 'NATIONAL'),
('Brazil', 'BRA', 83, 'CONMEBOL', NULL, 'NATIONAL'),
('Italy', 'ITA', 82, 'UEFA', NULL, 'NATIONAL'),
('Morocco', 'MOR', 79, 'CAF', NULL, 'NATIONAL'),
('Croatia', 'CRO', 79, 'UEFA', NULL, 'NATIONAL'),
('Denmark', 'DEN', 78, 'UEFA', NULL, 'NATIONAL'),
('Norway', 'NOR', 77, 'UEFA', NULL, 'NATIONAL'),
('Poland', 'POL', 77, 'UEFA', NULL, 'NATIONAL'),
('Sweden', 'SWE', 77, 'UEFA', NULL, 'NATIONAL'),
('Ukraine', 'UKR', 77, 'UEFA', NULL, 'NATIONAL'),
('Austria', 'AUT', 77, 'UEFA', NULL, 'NATIONAL'),
('United States', 'USA', 77, 'CONCACAF', NULL, 'NATIONAL'),
('Czechia', 'CZE', 76, 'UEFA', NULL, 'NATIONAL'),
('Scotland', 'SCO', 76, 'UEFA', NULL, 'NATIONAL'),
('Ghana', 'GHA', 76, 'CAF', NULL, 'NATIONAL'),
('Mexico', 'MEX', 76, 'CONCACAF', NULL, 'NATIONAL'),
('Ireland', 'IRE', 74, 'UEFA', NULL, 'NATIONAL'),
('Hungary', 'HUN', 74, 'UEFA', NULL, 'NATIONAL'),
('Wales', 'WAL', 73, 'UEFA', NULL, 'NATIONAL'),
('Canada', 'CAN', 73, 'CONCACAF', NULL, 'NATIONAL'),
('Romania', 'ROM', 72, 'UEFA', NULL, 'NATIONAL'),
('Finland', 'FIN', 71, 'UEFA', NULL, 'NATIONAL'),
('Iceland', 'ICE', 71, 'UEFA', NULL, 'NATIONAL'),
('Australia', 'AUS', 71, 'AFC', NULL, 'NATIONAL'),
('Northern Ireland', 'NIR', 70, 'UEFA', NULL, 'NATIONAL'),
('Qatar', 'QAT', 70, 'AFC', NULL, 'NATIONAL'),
('New Zeland', 'NZE', 68, 'OFC', NULL, 'NATIONAL'),
('China', 'CHI', 65, 'AFC', NULL, 'NATIONAL'),
('Bolivia', 'BOL', 66, 'CONMEBOL', NULL, 'NATIONAL'),
('India', 'IND', 57, 'AFC', NULL, 'NATIONAL');
